
runtime: go
api_version: go1

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /js
  static_dir: static/js

- url: /site.webmanifest
  static_files: static/site.webmanifest
  upload: static/site.webmanifest

- url: /browserconfig.xml
  static_files: static/browserconfig.xml
  upload: static/browserconfig.xml

- url: /images/favicon.ico
  static_files: static/images/favicon.ico
  upload: static/favicon.ico

- url: /images/favicon-32x32.png
  static_files: static/images/favicon-32x32.png
  upload: static/images/favicon-32x32.png

- url: /images/favicon-16x16.png
  static_files: static/images/favicon-16x16.png
  upload: static/images/favicon-16x16.png

- url: /images/android-chrome-192x192.png
  static_files: static/images/android-chrome-192x192.png
  upload: static/images/android-chrome-192x192.png

- url: /images/android-chrome-384x384.png
  static_files: static/images/android-chrome-384x384.png
  upload: static/images/android-chrome-384x384.png

- url: /images/mstile-150x150.png
  static_files: static/images/mstile-150x150.png
  upload: static/images/mstile-150x150.png

- url: /images/apple-touch-icon.png
  static_files: static/images/apple-touch-icon.png
  upload: static/images/apple-touch-icon.png

- url: /images/safari-pinned-tab.svg
  static_files: static/images/safari-pinned-tab.svg
  upload: static/images/safari-pinned-tab.svg


- url: /.*
  script: _go_app

